salesforce:
  password: "![EPKWrTLOZbAjmS43irAI0Q==]"
  consumerKey: "![6sUJBrdc18hgVJi10u/5En26AHPvmEUDodlsPxZMVdMQfk1GIqYthtWydfkCGZbz0hQk/t9HPMKQDyeQoqJQhKDfr2ps6z27UGPq8SPi4PR8qgxBAl2h1Q==]"
 
google:
  securedClientId: "![ksFyd6O8T2W5ED7u9G5GmkC+NQ4qc5JgsM3EUzSRtVxegV590n18+AMOJDe0acX0Q9ow9wLhoMpAHBIzwrbtI4qijekEF6Cx3WEkLCt+6mA=]"
  securedClientSecret: "![BMK+5yInW7W7IAEiLC/hmi1Gm94KjXx4+SkydnLSlsf4kTfBowq+MQ==]"
  securedDeveloperToken: "![pUcwAXbuh581aCbqZdEpL65Nqx7Zygkc]"
  securedRefreshToken: "![dH0NX/OCSFLpaSkM/HmeqbKn2BijUxp24KjnqdI8sro+YES1ppXHU7gWRDoM8ogyvX31WcfxJAaTcarHyUjjzhKczwynTv/N4juvOROSRu/Ypil+UELzrLIEZlar7er0Cs4xbIkFQ88=]"
  securedCustomerId: "![2q+WFTOjE1Lc9JDY+/mXAg==]"
  securedKey: ""
  securedAccessToken: ""
  
facebook:
  securedAccessToken: "![K8IIDqlOsVUC++8ofHbvGOmYMzHS21j3SRQxAFfE32pCgZDYLQaaF/pFYZM0/d+lPhyGuMpCLMWY3Q9yEVkI+Y1874tKKHcCJkU57lTRW++lorKDTpkZxKHBJ02D0wND2W0tpOjMrlECKkn2ubeDSPJZiSyZlXpFSjGe0vzIz8itDh+J0BuMFQcsYjm3DxUOhQu688Ri9Rr/N1YOpGwSS4BKg4w7GCAch3Bn76Ob3s6UKW+OmBdKGlXVXQEiHQmMzVFw3HzJmbbx5HSZO3iiCQ==]"
              
googlead:  
  privateKey: "![2YACqwj5f157zozi7qAgNA33PSWbFfRn8lnBhj1P1OfO3+43YehqB8xFSFEFBlzc]"
  clientEmail: "![kbq/2sAOFzyOt+kW0aFYFHcCB6VIfMxRebTdDVP+Fl+wJAmhzd9sYET1eIxOzUah++BSZImmHURJkXg1lz43ZxQrJQe5TQfqnnvOUKuWYVFpPzN4PfJxQQ==]"
