salesforce:
  password: "![alFJRXNXggdd2z5b2V0bxw==]"
  consumerKey: "![HUQbRBWxAZYQevEJcySTSlSirMcn2IvJ1VTor+b3Q8khky3usGu57jeLu4WMXiySPUMfuMbrybs2cJoTPQ0PV/I66guJfAd/+4aYs/SjrluOXkEMyGVlCg==]"
 
facebook:
  token: "![s3DYH4J638j/TX80KuORDeTeTJZ7jbOXhCfdErCldPsNELFyliaWdRMtAMxxsywm/CUd0b8izGTD0cYdkXoO8B370vzthdHqMf71DMhTcKxgxaNfWsYB9CdvOQC2yklmg8rmN9+9ydzYrP40Dpx5pe8hbCwcGaRVIYD/WB8homP+USGY6DXlr3iS+ehl58xAGpcyMWN5KJcHJUiG88Yv4rPLI6s9vIOuIaTgWI6xzO+xm+qjtyNlbEma7sTTpeZaeCLik4EkPd8=]"
        



