salesforce:
  password: "![EPKWrTLOZbAjmS43irAI0Q==]"
  consumerKey: "![6sUJBrdc18hgVJi10u/5En26AHPvmEUDodlsPxZMVdMQfk1GIqYthtWydfkCGZbz0hQk/t9HPMKQDyeQoqJQhKDfr2ps6z27UGPq8SPi4PR8qgxBAl2h1Q==]"
 
facebook:
  token: "![MfbHiGVvAN/O5e3M48dPcp+V6fYXbnhYfNRAMmL9ebELKeHL4gtiNj7P3WMV07SDnXTzfw29O/XYFiZ34rxrU8aFLz6Yjmzra0hHO/pU1g79c5JOZTTrfARJymTBlOaVpo4ZBmhCHzb3dK+ZBg1E9+LNCRnhBNID5wL6AU2+MIokpe37DW0SIXvqg2LGeVPp07xuNZCi9xhE/7kr4P9C0eCmN5NiPnpJM5xfO0ivDcIsawqjhFxXA7bc4/58d0j50z1+8J5b9Ps=]"
        



