salesforce:
    user: "mulesoftintegration@bnwuae.com.partial"
    cert-password: "${secure::salesforce.password}"
    certificate: "uat-Certificate/00DWI000003aLfJ.jks"
    security:
        url: "https://test.salesforce.com/services/oauth2/token"
    consumer:
        key: "${secure::salesforce.consumerKey}"


facebook:
    token: "${secure::facebook.token}"